<a href="https://colab.research.google.com/github/harshsrivastava096/Python-Libraries/blob/numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import numpy
import numpy as np

In [ ]:
#creation of list
l=[1,2,3,4,5]
type(l)
l

[1, 2, 3, 4, 5]

In [ ]:
#array creation
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#l+2-> list+int not possible

In [ ]:
#element-wise operation
arr+2

array([3, 4, 5, 6, 7])

In [ ]:
#adding 2 lists
l1=[1,2,3,4,5]
l2=[6,7,8]
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
#adding 2 arrays
# ar1=np.array([1,2,3,4,5])
# ar2=np.array([6,7,8])
# ar1+ar2

In [ ]:
#Shapes-> an attribute of numpy that shows the shape of the array
# (row,)-> 1D array
# (row,column)-> 2D array
# (depth,row,column)-> 3D array
# (height,depth,row,column)-> 4D array
# As the number of demensions increase, the number of paramenters in shapes also increases

In [ ]:
#lists consume more memory and time than array
#time-> library
#process_time -> class
from time import process_time
python_list=[i for i in range(10000)] #creation of list with range 0-9999
start_time=process_time() #stores the recorded start time
python_list=[i+2 for i in python_list] #element-wise addition in the list
end_time=process_time() #stores the recorded end time
print(end_time-start_time) #displays how much time it took to perform the element-wise operation

0.00031457100000009675


In [ ]:
arr=np.array([i for i in range(10000)]) #creation of an array with range 0-9999
start_time=process_time()#stores the recorded start time
arr += 2 #arr = arr+2-> performs element-wise operation without using for loop
end_time=process_time()#stores recorded end time
print(end_time-start_time) #displays how much time it took to perform the element-wise operation

0.00011852100000009358


In [ ]:
l=[1,2,3]
l
ar=np.array([1,2,3])
ar
#ndim-> attribute that shows how many dimension are there for the array
ar.ndim
ar2=np.array([[1,2,3],[4,5,6]])
ar2.ndim
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Functions
# dtype-> attribute of numpy which shows the datatype of the array
#ar2.dtype
# l=[1,2,3]
# type(l)
ar=np.array([1.5,2.5,3.5])
ar.dtype

dtype('float64')

In [ ]:
#upscaling-> converting the array into the datatype of the element having the highest priority in the array
ar=np.array([1,2,3,4.5])
ar

array([1. , 2. , 3. , 4.5])

In [ ]:
#priority list
# bool-> priority 6
# int-> priority 5
# float->priority 4
# complex-> priority 3
# str-> priority 2
# set-> converting the datatype to object->priority 1
# dict-> converting the datatype to object->priority 1

In [ ]:
#u64-> unicode 64-> 64 is size
arr=np.array([True])#scalar value
arr=np.array([True,1])
arr=np.array([True,1,2.5])
arr=np.array([True,1,2.5,6+5j])
arr=np.array([True,1,2.5,6+5j,"numpy"])
arr=np.array([True,1,2.5,6+5j,"numpy",{1,2}])
arr=np.array([True,1,2.5,6+5j,"numpy",{1,2},{1:"a",2:"b"}])

print(arr)
print(arr.dtype)

[True 1 2.5 (6+5j) 'numpy' {1, 2} {1: 'a', 2: 'b'}]
object


In [ ]:
l=[1,2,3,4,5]
t=(1,2,3)
np.array(t) # array can convert both list and tuple into array

array([1, 2, 3])

In [ ]:
#[20,40,60,80,30,50]
arr1=np.array([20,40,60,80,30,50])
arr1

array([20, 40, 60, 80, 30, 50])

In [ ]:
ar2=np.array([10,20,35.6,80])
print(ar2)
ar2.dtype

[10.  20.  35.6 80. ]


dtype('float64')

In [ ]:
ar3=np.array([10,"numpy",30,"hi"])
ar3.dtype

dtype('<U21')

In [ ]:
l=["bye",6+8j,{"d":12,"e":45},67.9]
ar4=np.array(l)
ar4
# ar4.dtype

array(['bye', (6+8j), {'d': 12, 'e': 45}, 67.9], dtype=object)

In [ ]:
#typecasting using astype()
arr=np.array(["1","2","67.78","65"])
bl=arr.astype(float)
print(bl)
bl.dtype

[ 1.    2.   67.78 65.  ]


dtype('float64')

In [ ]:
# convert it into float, str, object

In [ ]:
#dtype
#astype
#ndim-> n no. of dimensions

In [ ]:
arr= np.array([1,2,3,4])
arr
arr.ndim

1

In [ ]:
arr2=np.array([[1,2,5],
              [3,4,6]])
print(arr2)
arr2.ndim

[[1 2 5]
 [3 4 6]]


2

In [ ]:
arr2=np.array([[24,65,78],
              [36,87,35],
               [64,57,87]])
print(arr2)
print(arr2.ndim)
print(arr2.shape) #tuple(rows,columns)
arr2.size

[[24 65 78]
 [36 87 35]
 [64 57 87]]
2
(3, 3)


9

In [ ]:
arr3=np.array([[[[24,65,78],
              [36,87,35],
               [64,57,87]],

               [[56,87,37],
                [45,92,35],
                [45,98,55]]],


               [[[24,65,78],
              [36,87,35],
               [64,57,87]],

               [[56,87,37],
                [45,92,35],
                [45,98,55]]]])
print(arr3)
print(arr3.ndim)
arr3.shape#tuple(depth,row,column)

[[[[24 65 78]
   [36 87 35]
   [64 57 87]]

  [[56 87 37]
   [45 92 35]
   [45 98 55]]]


 [[[24 65 78]
   [36 87 35]
   [64 57 87]]

  [[56 87 37]
   [45 92 35]
   [45 98 55]]]]
4


(2, 2, 3, 3)

In [ ]:
(2,2,3,2)#tuple(height,depth,rows,columns)

(2, 2, 3, 2)

In [ ]:
arr3.size

36

In [ ]:
#create an array with shape (3,4,2) and find out the size of the elements

In [ ]:
arr=np.array([[2,3,4,8],[5,6,7,9]])
print(arr.shape)
print(arr.ndim)
arr

(2, 4)
2


array([[2, 3, 4, 8],
       [5, 6, 7, 9]])

In [ ]:
#.reshape()-> we can reshape an original array by keeping the product of the shape of the original array as same.
arr_reshape=arr.reshape(2,2,2)
print(arr_reshape.ndim)
print(arr_reshape.shape)
print(arr_reshape.size)
arr_reshape

3
(2, 2, 2)
8


array([[[2, 3],
        [4, 8]],

       [[5, 6],
        [7, 9]]])

In [ ]:
# (5,10)-> original
# (5,5,2)-> reshape
# (2,5,5)
# (5,2,5)

In [ ]:
# np.zeros()-> creates an array filled with values as 0
z=np.zeros((5,10))
# print(z.reshape(5,5,2))
# print(z.reshape(2,5,5))
# print(z.reshape(5,2,5))
z.dtype


dtype('float64')

In [ ]:
#np.ones((shape))-> creates an array filled with values as 1
one=np.ones((3,5,4))
one.dtype

dtype('float64')

In [ ]:
(3,5,4)
(12,5)
(15,4)
(3,5,2,2)
(2,15,2)

(2, 15, 2)

In [ ]:
#np.full(shape,value)-> Creates an array filled with the given value
ar1=np.full((4,6),20)
ar1

array([[20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [ ]:
(4,6)

(4, 6)

In [ ]:
# product of (5,10)-> 50
ar2=np.zeros((5,10))
ar2
ar2.shape
ar2.reshape(2,5,5)
# ar2.reshape(5,2,6)


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
ar2=np.full((4,6),'🤩🔥')
print(ar2.reshape(12,2))
arr2.ndim

[['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']
 ['🤩🔥' '🤩🔥']]


2

In [ ]:
# #range(SV,EV-1,updation)
# l=[]
# for i in range(10,20,2.5):
#   #
#   l.append(i)
# l



In [ ]:
#arange()-> creates a range of values
# starting value-> Inclusive
# ending value--> exlusive
# space in between--> the difference between each element in the array
var=np.arange(20,100,.5)
print(var.size)
var

160


array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5,
       31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. ,
       36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5,
       42. , 42.5, 43. , 43.5, 44. , 44.5, 45. , 45.5, 46. , 46.5, 47. ,
       47.5, 48. , 48.5, 49. , 49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5,
       53. , 53.5, 54. , 54.5, 55. , 55.5, 56. , 56.5, 57. , 57.5, 58. ,
       58.5, 59. , 59.5, 60. , 60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5,
       64. , 64.5, 65. , 65.5, 66. , 66.5, 67. , 67.5, 68. , 68.5, 69. ,
       69.5, 70. , 70.5, 71. , 71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5,
       75. , 75.5, 76. , 76.5, 77. , 77.5, 78. , 78.5, 79. , 79.5, 80. ,
       80.5, 81. , 81.5, 82. , 82.5, 83. , 83.5, 84. , 84.5, 85. , 85.5,
       86. , 86.5, 87. , 87.5, 88. , 88.5, 89. , 89.5, 90. , 90.5, 91. ,
       91.5, 92. , 92.5, 93. , 93.5, 94. , 94.5, 95

In [ ]:
#Task1: np.arange()- first find the size, 4 reshape

In [ ]:
#linspace-> Creates a range of values. Default size is 50.
#It creates 50 elements within the given range having equal space in between
arr=np.linspace(20,40)
print(arr.size)
print(arr)
arr.ndim

50
[20.         20.40816327 20.81632653 21.2244898  21.63265306 22.04081633
 22.44897959 22.85714286 23.26530612 23.67346939 24.08163265 24.48979592
 24.89795918 25.30612245 25.71428571 26.12244898 26.53061224 26.93877551
 27.34693878 27.75510204 28.16326531 28.57142857 28.97959184 29.3877551
 29.79591837 30.20408163 30.6122449  31.02040816 31.42857143 31.83673469
 32.24489796 32.65306122 33.06122449 33.46938776 33.87755102 34.28571429
 34.69387755 35.10204082 35.51020408 35.91836735 36.32653061 36.73469388
 37.14285714 37.55102041 37.95918367 38.36734694 38.7755102  39.18367347
 39.59183673 40.        ]


1

In [ ]:
# 0.40816327

#  31.02040816-30.6122449

In [ ]:
a=np.linspace(-50,200).reshape(2,5,5)
print(a.size)
a

50


array([[[-50.        , -44.89795918, -39.79591837, -34.69387755,
         -29.59183673],
        [-24.48979592, -19.3877551 , -14.28571429,  -9.18367347,
          -4.08163265],
        [  1.02040816,   6.12244898,  11.2244898 ,  16.32653061,
          21.42857143],
        [ 26.53061224,  31.63265306,  36.73469388,  41.83673469,
          46.93877551],
        [ 52.04081633,  57.14285714,  62.24489796,  67.34693878,
          72.44897959]],

       [[ 77.55102041,  82.65306122,  87.75510204,  92.85714286,
          97.95918367],
        [103.06122449, 108.16326531, 113.26530612, 118.36734694,
         123.46938776],
        [128.57142857, 133.67346939, 138.7755102 , 143.87755102,
         148.97959184],
        [154.08163265, 159.18367347, 164.28571429, 169.3877551 ,
         174.48979592],
        [179.59183673, 184.69387755, 189.79591837, 194.89795918,
         200.        ]]])

In [ ]:
#Task: Create an array of your choice using linspace. show me the array size as well as the array

In [ ]:
l=[1,2,3,4,5]
l[2]

3

In [ ]:
arr=np.array([1,2,3,4,5])
arr[2]

np.int64(3)

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#arr2[row,column]
arr2[1,1]

np.int64(5)

In [ ]:
#Task: Give me the code to access 9, 3, 4, 8

In [ ]:
#Task: Create a 2D array of range 20-50 shape(2,5)

In [ ]:
ar = np.arange(20,50,3).reshape(2,5)
ar

array([[20, 23, 26, 29, 32],
       [35, 38, 41, 44, 47]])

In [ ]:
#Task: Tell me how you will get these elements--> 44, 23, 41, 32 give the code and output

In [ ]:
#random.rand-> 0-1 any random values are created
r=np.random.rand(100)
r=np.random.randint(20,40,5) #creates random given number of integer values between the given range
r=np.random.randn(5) #creates the given number of random values who has a normal distribution where mean=0 and standard_deviation=1
r
# r.size
# r.dtype


array([ 0.01896634, -0.22749814,  0.2782418 , -0.66459159,  0.82138073])

In [ ]:
#Task: Create a range of values using randint and give 10 random values from that range

In [ ]:
ar_eye=np.eye(4) #Creates an identity matrix having given number of rows and columns
print(ar_eye)
ar_eye.shape

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(4, 4)

In [ ]:
#Task: Create an identity matrix having shape (6,6)

In [ ]:
arr=np.arange(10,80,3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79])

In [ ]:
#Slicing--> var[stratingindex:endingindex+1:updation]
#Remember-> ending index is exclusive(index will always be -1)

In [ ]:
# arr[4:10:3]
arr[2:13+1:4]

array([16, 28, 40])

In [ ]:
arr[5:]
arr[::-1]

array([79, 76, 73, 70, 67, 64, 61, 58, 55, 52, 49, 46, 43, 40, 37, 34, 31,
       28, 25, 22, 19, 16, 13, 10])

In [ ]:
arr=np.arange(10,80,3).reshape(4,6)
arr

array([[10, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79]])

In [ ]:
# arr[1,2]
# syntax--> var[row slicing,column slicing]
# var[RSI:REI+1:Up,CSI:CEI+1:Up]
arr[1:2:1,1:5:1]
# (10,13,28,31)
arr[0:2,0:2]
(34,37,52,55)
arr[1:3,2:4]
arr[:,4:]
arr[0:4,4:6]
arr[0:,4:]
arr[0:4,0:3]


array([[10, 13, 16],
       [28, 31, 34],
       [46, 49, 52],
       [64, 67, 70]])

In [ ]:
arr[1:2,1:5]

array([[31, 34, 37, 40]])

In [ ]:
ar1=np.linspace(0,1,10)
ar1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#element-wise operation between two arrays is called as broadcasting
#Performing element-wise operation on an array with a scalar value is called as vectorization
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
# l1*l2

a1=np.array(l1)
print(a1)
a2=np.array(l2)
# print(a2)
# Vectorization-nomatter if you change the number of elements in the array, it will work
a1+2
# Broadcasting- if you give different number of elements(size of elements)it will not work->
#it only works if the array sizes are same
a1+a2

[1 2 3 4 5]


array([ 7,  9, 11, 13, 15])

In [ ]:
#Arithmatic operations on scalar values
# a1+2
# a1-2
# a1*2
# a1/2
# a1//2
# a1%2


In [ ]:
#Arithmatic operations between two arrays
print(a1)
print(a2)
# a1+a2
# a2-a1
# a1*a2
# a1/a2
# a1//a2
#a1**a2

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
# Task:
#Create 2D array shape(3,4) and add it with 6, then substract it with 3,
# multiply it with 4, and then divide it with 2
#tell me whether this is vecotiration or broadcasting

In [ ]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr+6)
print(arr-3)
print(arr*4)
print(arr/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 0  4  8 12]
 [16 20 24 28]
 [32 36 40 44]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [ ]:
#Task: Create 2 2D arrays with shape(3,4) perform addition, substraction, multiplation, divide, and power

In [ ]:
#boolean filtering
arr=np.arange(4,12)
arr[arr>6]
print(arr>6)
arr

[False False False  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# l=[ 4,  5,  6,  7,  8,  9, 10, 11]
# l>6

# l1=[]
# for i in l:
#   if i%2!=0:
#     l1.append(i)
# l1


In [ ]:
#Task:
#Create a 1D array within the range of 20-50 and
#filter out numbers which are greater than 32 but less than 45

In [ ]:
#in boolean filtering if we have multiple conditions at once,
#we cannot use logical operators, we have to use bitwise operators
arr2=np.arange(20,51)
print(arr2)
#arr2[32<arr2<45]--> error
#arr2[(arr2>32)and(arr2<45)]-->error
arr2[(arr2>32)&(arr2<45)]

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
#Task: Create a 2d array(1-18), change it shape once to (3,6) then to (2,9) and then filter out numbers which are even

In [ ]:
#statistics
#mean, median, mode(no there in numpy), standard deviation, variance

arr=np.array([4,3,6,2,7,9,10,8,1])
#mean-> average(sum of the elements divided by number of elements)
np.mean(arr)
np.median(arr)
#for median the values are first sorted, if the number of values are odd, you will get an whole number
#if it is even, then a value will be in decimal
#but the datatype will be float
#(1,2,3,4,6,7,8,9,10)-> sorted array
#np.mode(arr)--> numpy does not have mode
np.var(arr)#-> how much data is spread/what the spread of the data is
np.std(arr)#--> how far a data is from the mean

np.float64(3.02254900194121)

In [ ]:
#Rounding
#np.ceil()-> rounding the figure upwards( towards +ve infinity)/rounding up the decimal to the next whole number
#np.floor()-> rounding the figure downwards(towards -ve infinity)/rounding the decimal to the previous whole number
#np.around()-> follows Banker's rounding
#Banker's rounding rules:
#1) If the decimal point is less than .5 then it will round up the value to the previous whole number
#2) If the decimal point is more than .5 then it will round up the value to the next whole number
#3) If the decimal point is exactly .5 then it will round up the value to the nearest even number
#3.5-> 3,4 -> 4
#4.5-> 4,5 -> 4
a=np.array([1,2,3.5,4.5])
np.ceil(a)
np.floor(a)
np.around(a)
# [1.,2.,4.,5.]

array([1., 2., 4., 4.])

In [ ]:
a=np.array([1,2,3.5,-1.5])
np.around(a)

array([ 1.,  2.,  4., -2.])

In [ ]:
#Fancy indexing
a=np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
ar=np.arange(5,21).reshape(4,4)
# ar.ndim
# ar.shape

In [ ]:
#7,6,9,10,5
# ar[[2,1,4,5,0]]
#10,8,19,9,16
print(ar)
ar[[1,0,3,1,2],[1,3,2,0,3]]

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([10,  8, 19,  9, 16])

In [ ]:
#Task: create a 3x4 matrix range will be 1-12 and give me these elements in order: 6,2,8,12,3

In [ ]:
#turnery operator--> true_block condition false_block
#np.where()-> used to replace values (condition,true,false)

In [ ]:
ar=np.array([1,2,3,4,5,6,7,8,9])
np.where(ar>5,0,ar)

array([1, 2, 3, 4, 5, 0, 0, 0, 0])

In [ ]:
#Task: create an array with range 6-22 and replace the even numbers with 1 and odd numbers with 0

In [ ]:
#Task: create an array with 12 values convert it into 3d array
#where the depth should be 3 and replace the middle 2d array with 0.
#Use np.where()

In [ ]:
ar=np.arange(1,13).reshape(3,2,2)
ar
np.where(ar==ar[1],0,ar)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 0,  0],
        [ 0,  0]],

       [[ 9, 10],
        [11, 12]]])